FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/InnoTrack.WebApi/InnoTrack.WebApi.csproj", "src/InnoTrack.WebApi/"]
RUN dotnet restore "src/InnoTrack.WebApi/InnoTrack.WebApi.csproj"
COPY . .
WORKDIR "/src/src/InnoTrack.WebApi"
RUN dotnet build "InnoTrack.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "InnoTrack.WebApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InnoTrack.WebApi.dll"]
