// <auto-generated />
using System;
using InnoTrack.WebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace InnoTrack.WebApi.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210123811_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnoTrack.WebApi.Entities.Innovation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "russian")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "AuthorName", "ProductName", "TechnologyName", "OrganizationName" });

                    b.Property<string>("TechnologyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("Innovations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Марина Галкина",
                            DateTime = new DateTime(2021, 2, 7, 14, 48, 37, 333, DateTimeKind.Utc).AddTicks(4046),
                            OrganizationEmail = "elizaveta_turova@mail.ru",
                            OrganizationName = "ИнноТех",
                            ProductName = "Графический чип",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Виталий Кондратьев",
                            DateTime = new DateTime(2021, 10, 23, 3, 33, 20, 196, DateTimeKind.Utc).AddTicks(3142),
                            OrganizationEmail = "vladimir_odincov88@gmail.com",
                            OrganizationName = "СофтТек",
                            ProductName = "Устройство связи",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Евгений Матвеев",
                            DateTime = new DateTime(2023, 5, 29, 10, 38, 4, 983, DateTimeKind.Utc).AddTicks(4273),
                            OrganizationEmail = "arsenii.bespalova@hotmail.com",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Аналитическая платформа",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Сергей Агафонов",
                            DateTime = new DateTime(2021, 1, 7, 20, 56, 26, 82, DateTimeKind.Utc).AddTicks(2865),
                            OrganizationEmail = "darya96@yahoo.com",
                            OrganizationName = "НаноТех",
                            ProductName = "Сенсор",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Анастасия Дмитриев",
                            DateTime = new DateTime(2021, 5, 8, 2, 25, 16, 606, DateTimeKind.Utc).AddTicks(5312),
                            OrganizationEmail = "egor_kiseleva@yandex.ru",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Даниил Брагина",
                            DateTime = new DateTime(2024, 4, 11, 21, 28, 0, 834, DateTimeKind.Utc).AddTicks(4279),
                            OrganizationEmail = "ignatii29@hotmail.com",
                            OrganizationName = "НаноТех",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Георгий Рожкова",
                            DateTime = new DateTime(2021, 9, 20, 20, 58, 25, 903, DateTimeKind.Utc).AddTicks(281),
                            OrganizationEmail = "varvara.shiryaev@yandex.ru",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Раиса Калинин",
                            DateTime = new DateTime(2021, 1, 26, 19, 33, 9, 205, DateTimeKind.Utc).AddTicks(8963),
                            OrganizationEmail = "vitalii40@mail.ru",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Сенсор",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Анфиса Константинова",
                            DateTime = new DateTime(2023, 5, 26, 12, 54, 51, 828, DateTimeKind.Utc).AddTicks(1530),
                            OrganizationEmail = "zhanna_panfilova@yahoo.com",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Графический чип",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Лариса Филиппова",
                            DateTime = new DateTime(2023, 5, 10, 21, 21, 35, 216, DateTimeKind.Utc).AddTicks(105),
                            OrganizationEmail = "vera.orekhov@hotmail.com",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Устройство связи",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "Фёдор Моисеев",
                            DateTime = new DateTime(2020, 5, 28, 18, 58, 4, 588, DateTimeKind.Utc).AddTicks(6270),
                            OrganizationEmail = "semyon33@yahoo.com",
                            OrganizationName = "РобоТех",
                            ProductName = "Сенсор",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "Арина Филатов",
                            DateTime = new DateTime(2024, 2, 4, 23, 20, 3, 751, DateTimeKind.Utc).AddTicks(2911),
                            OrganizationEmail = "vladislav_panfilova52@mail.ru",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Устройство связи",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "Регина Никифорова",
                            DateTime = new DateTime(2024, 4, 4, 1, 29, 23, 332, DateTimeKind.Utc).AddTicks(9672),
                            OrganizationEmail = "arkadii.tikhonov39@ya.ru",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "Зинаида Моисеева",
                            DateTime = new DateTime(2024, 3, 2, 13, 15, 32, 248, DateTimeKind.Utc).AddTicks(3598),
                            OrganizationEmail = "regina_kosheleva59@hotmail.com",
                            OrganizationName = "РобоТех",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Геннадий Иванова",
                            DateTime = new DateTime(2023, 2, 7, 8, 3, 19, 703, DateTimeKind.Utc).AddTicks(3634),
                            OrganizationEmail = "marina54@gmail.com",
                            OrganizationName = "РобоТех",
                            ProductName = "Сенсор",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 16,
                            AuthorName = "Герман Королев",
                            DateTime = new DateTime(2021, 2, 25, 6, 26, 51, 664, DateTimeKind.Utc).AddTicks(7811),
                            OrganizationEmail = "igor_dementeva29@mail.ru",
                            OrganizationName = "ГиперСофт",
                            ProductName = "Сенсор",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 17,
                            AuthorName = "Анжелика Лаврентьев",
                            DateTime = new DateTime(2020, 5, 24, 14, 19, 39, 956, DateTimeKind.Utc).AddTicks(6736),
                            OrganizationEmail = "lavrentii_rogov@yandex.ru",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 18,
                            AuthorName = "Антонина Ефимов",
                            DateTime = new DateTime(2024, 11, 1, 0, 8, 53, 856, DateTimeKind.Utc).AddTicks(5098),
                            OrganizationEmail = "leonid45@yandex.ru",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Процессор",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 19,
                            AuthorName = "Ольга Крылов",
                            DateTime = new DateTime(2021, 6, 20, 5, 9, 58, 998, DateTimeKind.Utc).AddTicks(3575),
                            OrganizationEmail = "lyudmila.subbotina64@ya.ru",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 20,
                            AuthorName = "Фёдор Анисимова",
                            DateTime = new DateTime(2022, 9, 24, 3, 48, 23, 366, DateTimeKind.Utc).AddTicks(7817),
                            OrganizationEmail = "georgii_pestova50@ya.ru",
                            OrganizationName = "ИнноТех",
                            ProductName = "Система мониторинга",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 21,
                            AuthorName = "Василий Блохин",
                            DateTime = new DateTime(2022, 3, 23, 4, 42, 28, 272, DateTimeKind.Utc).AddTicks(5414),
                            OrganizationEmail = "aleksandr19@mail.ru",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Сенсор",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 22,
                            AuthorName = "Вячеслав Соколова",
                            DateTime = new DateTime(2020, 8, 30, 1, 17, 34, 144, DateTimeKind.Utc).AddTicks(2715),
                            OrganizationEmail = "ulyana.burova@ya.ru",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Аналитическая платформа",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 23,
                            AuthorName = "Анатолий Щербакова",
                            DateTime = new DateTime(2024, 6, 8, 0, 33, 43, 467, DateTimeKind.Utc).AddTicks(3604),
                            OrganizationEmail = "roman.sysoeva29@yahoo.com",
                            OrganizationName = "ТехноСтар",
                            ProductName = "Графический чип",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 24,
                            AuthorName = "Матвей Селезнева",
                            DateTime = new DateTime(2024, 8, 24, 21, 53, 9, 641, DateTimeKind.Utc).AddTicks(6384),
                            OrganizationEmail = "veronika_agafonov49@mail.ru",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Сенсор",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 25,
                            AuthorName = "Надежда Богданов",
                            DateTime = new DateTime(2024, 12, 9, 23, 9, 9, 684, DateTimeKind.Utc).AddTicks(4656),
                            OrganizationEmail = "olga.belyakova65@ya.ru",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Система мониторинга",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 26,
                            AuthorName = "Виталий Кулагина",
                            DateTime = new DateTime(2022, 7, 17, 1, 16, 38, 551, DateTimeKind.Utc).AddTicks(2612),
                            OrganizationEmail = "alla_knyazeva77@mail.ru",
                            OrganizationName = "ИнтелСистемы",
                            ProductName = "Процессор",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 27,
                            AuthorName = "Ангелина Капустина",
                            DateTime = new DateTime(2022, 10, 3, 20, 59, 13, 393, DateTimeKind.Utc).AddTicks(8434),
                            OrganizationEmail = "mikhail.belozerova@yahoo.com",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Устройство связи",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 28,
                            AuthorName = "Анна Абрамов",
                            DateTime = new DateTime(2021, 4, 30, 1, 2, 43, 108, DateTimeKind.Utc).AddTicks(5095),
                            OrganizationEmail = "roman52@mail.ru",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Графический чип",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 29,
                            AuthorName = "Наталья Алексеева",
                            DateTime = new DateTime(2022, 9, 29, 18, 19, 7, 210, DateTimeKind.Utc).AddTicks(2309),
                            OrganizationEmail = "darya_petrov95@mail.ru",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Система мониторинга",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 30,
                            AuthorName = "Арсений Белов",
                            DateTime = new DateTime(2020, 2, 27, 5, 43, 42, 593, DateTimeKind.Utc).AddTicks(8260),
                            OrganizationEmail = "viktor_naumova49@hotmail.com",
                            OrganizationName = "НаноТех",
                            ProductName = "Графический чип",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 31,
                            AuthorName = "Антон Дроздова",
                            DateTime = new DateTime(2022, 12, 9, 4, 13, 0, 838, DateTimeKind.Utc).AddTicks(431),
                            OrganizationEmail = "arina_seliverstov7@yahoo.com",
                            OrganizationName = "ТехноСтар",
                            ProductName = "Система мониторинга",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 32,
                            AuthorName = "Даниил Веселова",
                            DateTime = new DateTime(2020, 2, 11, 3, 56, 18, 913, DateTimeKind.Utc).AddTicks(2321),
                            OrganizationEmail = "albert8@yahoo.com",
                            OrganizationName = "ТехноСтар",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 33,
                            AuthorName = "Юлия Сергеева",
                            DateTime = new DateTime(2020, 5, 26, 23, 51, 32, 699, DateTimeKind.Utc).AddTicks(9874),
                            OrganizationEmail = "andrei_bykov@ya.ru",
                            OrganizationName = "ИнноТех",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 34,
                            AuthorName = "Степан Белозеров",
                            DateTime = new DateTime(2022, 8, 3, 21, 36, 30, 421, DateTimeKind.Utc).AddTicks(9147),
                            OrganizationEmail = "kira.chernov0@gmail.com",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Графический чип",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 35,
                            AuthorName = "Виктор Аксенова",
                            DateTime = new DateTime(2021, 8, 5, 19, 30, 13, 196, DateTimeKind.Utc).AddTicks(7770),
                            OrganizationEmail = "alyona_naumova@gmail.com",
                            OrganizationName = "ИнноТех",
                            ProductName = "Процессор",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 36,
                            AuthorName = "Артём Ширяев",
                            DateTime = new DateTime(2022, 12, 22, 5, 58, 57, 992, DateTimeKind.Utc).AddTicks(1948),
                            OrganizationEmail = "anton.kharitonova@ya.ru",
                            OrganizationName = "СофтТек",
                            ProductName = "Графический чип",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 37,
                            AuthorName = "Константин Быков",
                            DateTime = new DateTime(2020, 12, 27, 2, 31, 27, 430, DateTimeKind.Utc).AddTicks(6819),
                            OrganizationEmail = "rimma.mishina@yandex.ru",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Аналитическая платформа",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 38,
                            AuthorName = "Валерий Власов",
                            DateTime = new DateTime(2021, 3, 3, 23, 58, 55, 503, DateTimeKind.Utc).AddTicks(7978),
                            OrganizationEmail = "artyom41@ya.ru",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Сенсор",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 39,
                            AuthorName = "Зоя Киселев",
                            DateTime = new DateTime(2021, 1, 11, 3, 17, 6, 31, DateTimeKind.Utc).AddTicks(2007),
                            OrganizationEmail = "marina_eliseev@yahoo.com",
                            OrganizationName = "ГиперСофт",
                            ProductName = "Сенсор",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 40,
                            AuthorName = "Ярослав Шилов",
                            DateTime = new DateTime(2020, 7, 9, 12, 24, 5, 978, DateTimeKind.Utc).AddTicks(3430),
                            OrganizationEmail = "leonid.bogdanov58@gmail.com",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Процессор",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 41,
                            AuthorName = "Лариса Веселов",
                            DateTime = new DateTime(2021, 4, 3, 16, 24, 54, 340, DateTimeKind.Utc).AddTicks(1355),
                            OrganizationEmail = "grigorii.davydov@ya.ru",
                            OrganizationName = "НаноТех",
                            ProductName = "Графический чип",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 42,
                            AuthorName = "Олег Агафонова",
                            DateTime = new DateTime(2023, 8, 26, 10, 2, 24, 856, DateTimeKind.Utc).AddTicks(3884),
                            OrganizationEmail = "olga.kulagin@gmail.com",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 43,
                            AuthorName = "Антонина Беспалов",
                            DateTime = new DateTime(2023, 7, 12, 8, 47, 53, 207, DateTimeKind.Utc).AddTicks(9367),
                            OrganizationEmail = "naezhda.sitnikov89@yandex.ru",
                            OrganizationName = "ИнноТех",
                            ProductName = "Процессор",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 44,
                            AuthorName = "Виталий Мартынов",
                            DateTime = new DateTime(2021, 1, 11, 11, 55, 12, 464, DateTimeKind.Utc).AddTicks(2380),
                            OrganizationEmail = "anatolii24@yahoo.com",
                            OrganizationName = "ГиперСофт",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 45,
                            AuthorName = "Денис Селиверстов",
                            DateTime = new DateTime(2020, 1, 25, 1, 12, 10, 332, DateTimeKind.Utc).AddTicks(7704),
                            OrganizationEmail = "valentin_korolev28@mail.ru",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 46,
                            AuthorName = "Наталья Корнилов",
                            DateTime = new DateTime(2021, 5, 31, 3, 24, 37, 452, DateTimeKind.Utc).AddTicks(7971),
                            OrganizationEmail = "evgeniya_arkhipov@yandex.ru",
                            OrganizationName = "НаноТех",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Распознавание речи"
                        },
                        new
                        {
                            Id = 47,
                            AuthorName = "Лариса Марков",
                            DateTime = new DateTime(2024, 9, 15, 3, 47, 6, 97, DateTimeKind.Utc).AddTicks(9268),
                            OrganizationEmail = "viktor.sharov@hotmail.com",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Сенсор",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 48,
                            AuthorName = "Дарья Калинина",
                            DateTime = new DateTime(2020, 5, 15, 20, 25, 34, 262, DateTimeKind.Utc).AddTicks(7709),
                            OrganizationEmail = "semyon.timofeeva38@mail.ru",
                            OrganizationName = "ТехноСтар",
                            ProductName = "Аналитическая платформа",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 49,
                            AuthorName = "Антонина Маслов",
                            DateTime = new DateTime(2022, 3, 26, 17, 56, 58, 503, DateTimeKind.Utc).AddTicks(6005),
                            OrganizationEmail = "maksim.krylova26@yandex.ru",
                            OrganizationName = "ТехноСтар",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 50,
                            AuthorName = "Борис Селиверстова",
                            DateTime = new DateTime(2024, 3, 27, 23, 26, 36, 385, DateTimeKind.Utc).AddTicks(2384),
                            OrganizationEmail = "vera53@mail.ru",
                            OrganizationName = "ИнноТех",
                            ProductName = "Графический чип",
                            TechnologyName = "ИИ"
                        },
                        new
                        {
                            Id = 51,
                            AuthorName = "Александра Коновалова",
                            DateTime = new DateTime(2021, 7, 19, 16, 47, 28, 332, DateTimeKind.Utc).AddTicks(7535),
                            OrganizationEmail = "lidiya20@hotmail.com",
                            OrganizationName = "НаноТех",
                            ProductName = "Программное обеспечение",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 52,
                            AuthorName = "Таисия Богданова",
                            DateTime = new DateTime(2023, 6, 30, 16, 52, 7, 656, DateTimeKind.Utc).AddTicks(5558),
                            OrganizationEmail = "rimma_sysoev43@hotmail.com",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Сенсор",
                            TechnologyName = "IoT платформа"
                        },
                        new
                        {
                            Id = 53,
                            AuthorName = "Никита Блохин",
                            DateTime = new DateTime(2022, 7, 23, 19, 20, 13, 75, DateTimeKind.Utc).AddTicks(9590),
                            OrganizationEmail = "alevtina_silin11@hotmail.com",
                            OrganizationName = "СофтТек",
                            ProductName = "Система мониторинга",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 54,
                            AuthorName = "Степан Бобылева",
                            DateTime = new DateTime(2024, 8, 11, 12, 20, 57, 468, DateTimeKind.Utc).AddTicks(4623),
                            OrganizationEmail = "ignatii82@ya.ru",
                            OrganizationName = "ГиперСофт",
                            ProductName = "Процессор",
                            TechnologyName = "Нейросеть"
                        },
                        new
                        {
                            Id = 55,
                            AuthorName = "Нина Савельев",
                            DateTime = new DateTime(2020, 2, 23, 11, 17, 10, 555, DateTimeKind.Utc).AddTicks(8556),
                            OrganizationEmail = "taisiya55@hotmail.com",
                            OrganizationName = "ИнноТех",
                            ProductName = "Процессор",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 56,
                            AuthorName = "Даниил Петухов",
                            DateTime = new DateTime(2022, 3, 23, 14, 33, 41, 654, DateTimeKind.Utc).AddTicks(352),
                            OrganizationEmail = "lavrentii_kovalev86@gmail.com",
                            OrganizationName = "МегаТехнологии",
                            ProductName = "Устройство связи",
                            TechnologyName = "Квантовые вычисления"
                        },
                        new
                        {
                            Id = 57,
                            AuthorName = "Жанна Федоров",
                            DateTime = new DateTime(2021, 7, 25, 14, 48, 29, 350, DateTimeKind.Utc).AddTicks(2),
                            OrganizationEmail = "ulyana15@mail.ru",
                            OrganizationName = "ГлобалТех",
                            ProductName = "Процессор",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 58,
                            AuthorName = "Анна Константинова",
                            DateTime = new DateTime(2022, 11, 16, 13, 17, 53, 992, DateTimeKind.Utc).AddTicks(3747),
                            OrganizationEmail = "artyom37@ya.ru",
                            OrganizationName = "РобоТех",
                            ProductName = "Процессор",
                            TechnologyName = "Доставка"
                        },
                        new
                        {
                            Id = 59,
                            AuthorName = "Дмитрий Быкова",
                            DateTime = new DateTime(2019, 12, 27, 12, 44, 50, 997, DateTimeKind.Utc).AddTicks(581),
                            OrganizationEmail = "arina.zimina7@hotmail.com",
                            OrganizationName = "ИнноТех",
                            ProductName = "Устройство связи",
                            TechnologyName = "Машинное обучение"
                        },
                        new
                        {
                            Id = 60,
                            AuthorName = "Валерий Фокина",
                            DateTime = new DateTime(2020, 8, 22, 21, 12, 11, 285, DateTimeKind.Utc).AddTicks(5531),
                            OrganizationEmail = "arsenii_kuznecova@yahoo.com",
                            OrganizationName = "ИнфоСистемы",
                            ProductName = "Сенсор",
                            TechnologyName = "Квантовые вычисления"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
